name: Build the Plugin

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [published]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      - name: Build plugin
        run: ./gradlew buildPlugin
      - name: Upload artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: "PyDjinni-IntelliJ-Plugin"
          path: ./build/distributions/*
